on:
  pull_request:
    branches:
    - main
    
jobs:
  build-arduino:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: arduino/compile-sketches@v1.0.1
        with:
          cli-version: 0.31.0
          fqbn: Seeeduino:samd:seeed_XIAO_m0:usbstack=arduino,debug=off

          platforms: |
            - name: Seeeduino:samd
              source-url: https://files.seeedstudio.com/arduino/package_seeeduino_boards_index.json

          libraries: |
            - name: FlashStorage_SAMD
              version: 1.2.1
            - name: HID-Project
              version: 2.8.4
            - name: ArduinoJson
              version: 6.20.0
            - name: EncoderTool
              version: 3.2.0
          sketch-paths: FW/flux_arduino
          
          
  build-fluxapp:

    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - name: Checkout with submodules
      uses: actions/checkout@v3.5.2
      with:
        submodules: 'recursive'
        lfs: true

    - name: Create Executable
      uses: sayyid5416/pyinstaller@v1
      with:
        python_ver: '3.10'
        spec: 'APP/fluxapp.spec'
        requirements: 'APP/requirements.txt'
        upload_exe_with_name: 'FLUXAPP'
